### ISSUE TITLE
ChineseOpenConvert on Sublime 3 (3143)

### ISSUE THREAD

**Issue by cheng-tony** [rexdf/SublimeChineseConvert#1]
Hi , 
I use the ChineseOpenConvert in my sublime 3.
( Sublime Version: 3143, Operating System: Win7 x64)

And I can not invoke the functions.

Here is my log in the console:

--------------------------------------------------------------------------

Traceback (most recent call last):
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\SublimeChineseConvert.py", line 67, in init
    from .OpenCC import OpenCC
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\OpenCC\OpenCC.py", line 28, in <module>
    _OpenCC = swig_import_helper()
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\OpenCC\OpenCC.py", line 24, in swig_import_helper
    _mod = imp.load_module('_OpenCC', fp, pathname, description)
  File "./python3.3/imp.py", line 188, in load_module
ImportError: DLL load failed: 找不到指定的模組。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\SublimeChineseConvert.py", line 90, in init
    from .OpenCC import OpenCC
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\OpenCC\OpenCC.py", line 28, in <module>
    _OpenCC = swig_import_helper()
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\OpenCC\OpenCC.py", line 24, in swig_import_helper
    _mod = imp.load_module('_OpenCC', fp, pathname, description)
  File "./python3.3/imp.py", line 188, in load_module
ImportError: DLL load failed: 找不到指定的模組。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime&MinGW\Sublime Text 3 x64\Data\Packages\ChineseOpenConvert\SublimeChineseConvert.py", line 92, in init
    raise Exception("Can not load OpenCC, return")
Exception: Can not load OpenCC, return
warning: mnemonic d not found in menu caption Doi9t's packages
warning: mnemonic s not found in menu caption SortBy
warning: mnemonic n not found in menu caption Numbers
reloading /D/Sublime&MinGW/Sublime Text 3 x64/Data/Packages/ChineseOpenConvert/OpenCC/OpenCC.py

------------------------------------------------------
It seems that the OpenCC module can not be loaded by Python.
Please check this problem and give the feedback to me.

Thanks.

**Comment by rexdf** [comment]
I will have to rebuild the OpenCC module or you can use the old version of Sublime Text.

I will try it tomorrow

**Comment by rexdf** [comment]
I just test on 3143 and 3156. All versions are working as expected. 

Maybe you can uninstall SublimeChineseConvert and install from packagecontrol again.

PS:  possible issue that cause your situation:

1.  anitivirus software block SublimeChineseConvert to unzip dynamic python extensions.
2. you copyed the SublimeChineseConvert from other computer with NTFS permission, And Sublime Text 3 has no permission to write to SublimeChineseConvert folder
